window.MF_INTEGRATIONS = [
  { name: 'Airflow', abbr: 'AF', cat: 'Orchestration', desc: 'DAG definitions, task deps, run history, failure patterns.' },
  { name: 'Dagster', abbr: 'DG', cat: 'Orchestration', desc: 'Assets, jobs, schedules, materialization lineage.' },
  { name: 'Prefect', abbr: 'PF', cat: 'Orchestration', desc: 'Flows, deployments, run metadata into semantic graph.' },
  { name: 'Apache Spark', abbr: 'SP', cat: 'Orchestration', desc: 'Job lineage and cluster execution metadata.' },
  { name: 'dbt', abbr: 'dbt', cat: 'Transformation', desc: 'Manifest, model lineage, tests, docs, column deps.' },
  { name: 'SQLMesh', abbr: 'SM', cat: 'Transformation', desc: 'Model definitions and environment-aware lineage.' },
  { name: 'Dataform', abbr: 'DF', cat: 'Transformation', desc: 'BigQuery transformations and dependency graph.' },
  { name: 'Coalesce', abbr: 'CO', cat: 'Transformation', desc: 'Visual transformation nodes and column lineage.' },
  { name: 'Snowflake', abbr: 'SF', cat: 'Warehouses', desc: 'Schemas, tables, query history, access patterns.' },
  { name: 'BigQuery', abbr: 'BQ', cat: 'Warehouses', desc: 'Datasets, views, job metadata, cost signals.' },
  { name: 'Databricks', abbr: 'DB', cat: 'Warehouses', desc: 'Unity Catalog, notebooks, pipeline definitions.' },
  { name: 'Redshift', abbr: 'RS', cat: 'Warehouses', desc: 'Cluster schemas, tables, and query lineage.' },
  { name: 'Amazon Athena', abbr: 'AT', cat: 'Warehouses', desc: 'Glue catalog integration and query metadata.' },
  { name: 'Postgres', abbr: 'PG', cat: 'Databases', desc: 'Schemas, constraints, relationships, usage.' },
  { name: 'Supabase', abbr: 'SB', cat: 'Databases', desc: 'Postgres instances with RLS policy awareness.' },
  { name: 'MySQL', abbr: 'MY', cat: 'Databases', desc: 'Operational schemas and replication metadata.' },
  { name: 'MongoDB', abbr: 'MG', cat: 'Databases', desc: 'Collections, document schemas, aggregation pipelines.' },
  { name: 'ClickHouse', abbr: 'CH', cat: 'Databases', desc: 'Columnar schemas and materialized view lineage.' },
  { name: 'Fivetran', abbr: 'FT', cat: 'Ingestion', desc: 'Connector syncs, schema changes, source mappings.' },
  { name: 'Airbyte', abbr: 'AB', cat: 'Ingestion', desc: 'Sync jobs, streams, and destination lineage.' },
  { name: 'Stitch', abbr: 'ST', cat: 'Ingestion', desc: 'Replication metadata and schema drift detection.' },
  { name: 'Kafka', abbr: 'KF', cat: 'Streaming', desc: 'Topics, schemas, consumer/producer relationships.' },
  { name: 'Confluent', abbr: 'CF', cat: 'Streaming', desc: 'Schema Registry and stream processing lineage.' },
  { name: 'Apache Flink', abbr: 'FL', cat: 'Streaming', desc: 'Stream jobs and stateful operator graphs.' },
  { name: 'Looker', abbr: 'LK', cat: 'BI & Catalog', desc: 'Explores, dashboards, and metric definitions.' },
  { name: 'Tableau', abbr: 'TB', cat: 'BI & Catalog', desc: 'Workbooks, data sources, calculated fields.' },
  { name: 'Metabase', abbr: 'MB', cat: 'BI & Catalog', desc: 'Questions, dashboards, and SQL dependencies.' },
  { name: 'Apache Atlas', abbr: 'AL', cat: 'Governance', desc: 'Metadata entities, classifications, lineage import.' },
  { name: 'Collibra', abbr: 'CL', cat: 'Governance', desc: 'Business glossary and policy metadata sync.' },
  { name: 'Monte Carlo', abbr: 'MC', cat: 'Governance', desc: 'Observability incidents and data quality signals.' },
  { name: 'Acceldata', abbr: 'AD', cat: 'Governance', desc: 'Data observability, pipeline health, and anomaly signals.' },
  { name: 'Great Expectations', abbr: 'GX', cat: 'Governance', desc: 'Expectation suites and validation results.' },
  { name: 'GitHub', abbr: 'GH', cat: 'DevOps', desc: 'Repo structure, PR context for dbt and SQL changes.' },
  { name: 'GitLab', abbr: 'GL', cat: 'DevOps', desc: 'CI pipelines tied to data project deployments.' },
  { name: 'Kubernetes', abbr: 'K8', cat: 'DevOps', desc: 'Helm deployments and pod-level service mapping.' },
  { name: 'Docker', abbr: 'DK', cat: 'DevOps', desc: 'Container images for self-hosted Metroflow stacks.' },
  { name: 'S3', abbr: 'S3', cat: 'Storage', desc: 'Bucket paths, parquet schemas, partition lineage.' },
  { name: 'GCS', abbr: 'GC', cat: 'Storage', desc: 'Cloud storage assets and external table refs.' },
  { name: 'Azure Blob', abbr: 'AZ', cat: 'Storage', desc: 'Lakehouse file metadata and access logs.' },
  { name: 'Trino', abbr: 'TR', cat: 'Query Engines', desc: 'Federated query metadata across sources.' },
  { name: 'Presto', abbr: 'PR', cat: 'Query Engines', desc: 'Cross-catalog query lineage and table refs.' }
];